# Generated by Django 3.2.6 on 2023-05-21 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manejador_de_usuarios', '0001_initial'),
        ('manejador_de_pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia_clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.CharField(default=None, max_length=100)),
                ('tema', models.CharField(default=None, max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('medicamento', models.CharField(default=None, max_length=100)),
                ('autor_medico', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='manejador_de_usuarios.medico')),
                ('paciente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='manejador_de_pacientes.paciente')),
            ],
        ),
    ]
