# Generated by Django 3.2.6 on 2023-03-17 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manejador_de_pacientes', '0001_initial'),
        ('manejador_de_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia_clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_historia_clinica', models.BigIntegerField()),
                ('autor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='manejador_de_usuarios.medico')),
                ('paciente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='manejador_de_pacientes.paciente')),
            ],
        ),
    ]
