# Generated by Django 3.2.6 on 2023-03-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_de_registros_de_historias_clinicas', '0002_historia_clinica_registros'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia_clinica',
            name='diagnostico',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='fecha',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='medicamento',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='tema',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
