# Generated by Django 3.2.6 on 2023-03-18 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_de_adendas', '0002_auto_20230317_1819'),
        ('manejador_de_registros_de_historias_clinicas', '0003_auto_20230317_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia_clinica',
            name='registros',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='manejador_de_adendas.registro'),
        ),
    ]
