# Generated by Django 3.2.6 on 2023-04-12 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_de_usuarios', '0002_auto_20230317_1759'),
        ('manejador_de_registros_de_historias_clinicas', '0005_alter_historia_clinica_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historia_clinica',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='historia_clinica',
            name='registros',
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='autor_medico',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='manejador_de_usuarios.medico'),
        ),
        migrations.AlterField(
            model_name='historia_clinica',
            name='fecha',
            field=models.DateField(default=None),
        ),
    ]
