# Generated by Django 3.2.6 on 2023-04-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_de_registros_de_historias_clinicas', '0007_alter_historia_clinica_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia_clinica',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
