# Generated by Django 3.2.6 on 2023-05-04 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_de_registros_de_historias_clinicas', '0008_alter_historia_clinica_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historia_clinica',
            name='id_historia_clinica',
        ),
    ]
