# Generated by Django 3.2.6 on 2023-03-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_de_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfermero',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='usuario',
        ),
        migrations.AddField(
            model_name='enfermero',
            name='id_usuario',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='medico',
            name='id_usuario',
            field=models.BigIntegerField(default=None),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
