# Generated by Django 3.2.6 on 2023-05-11 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manejador_de_registros_de_historias_clinicas', '0001_initial'),
        ('manejador_de_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nit', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=50)),
                ('ips', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='manejador_de_adendas.ips')),
                ('ips_doctor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manejador_de_usuarios.medico')),
            ],
        ),
        migrations.CreateModel(
            name='Adenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.CharField(default=None, max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tema', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('autor_enfermero', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='manejador_de_usuarios.enfermero')),
                ('autor_medico', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='manejador_de_usuarios.medico')),
                ('historia_clinica', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='manejador_de_registros_de_historias_clinicas.historia_clinica')),
                ('servicio', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='manejador_de_adendas.servicio')),
            ],
        ),
    ]
