# Generated by Django 3.2.6 on 2023-03-17 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manejador_de_registros_de_historias_clinicas', '0001_initial'),
        ('manejador_de_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tema', models.CharField(max_length=50)),
                ('diagnostico', models.CharField(max_length=50)),
                ('historia_clinica', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='manejador_de_registros_de_historias_clinicas.historia_clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Adenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tema', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('autor_enfermero', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='manejador_de_usuarios.enfermero')),
                ('autor_medico', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='manejador_de_usuarios.medico')),
                ('registro', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='manejador_de_adendas.registro')),
            ],
        ),
    ]
