# Generated by Django 3.2.6 on 2023-05-21 02:49

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_de_adendas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adenda',
            name='descripcion',
            field=django_cryptography.fields.encrypt(models.CharField(default=None, max_length=100)),
        ),
        migrations.AlterField(
            model_name='adenda',
            name='diagnostico',
            field=django_cryptography.fields.encrypt(models.CharField(default=None, max_length=50)),
        ),
        migrations.AlterField(
            model_name='adenda',
            name='tema',
            field=django_cryptography.fields.encrypt(models.CharField(default=None, max_length=50)),
        ),
    ]
