# Generated by Django 3.2.6 on 2023-04-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_de_adendas', '0003_auto_20230412_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.CharField(max_length=20),
        ),
    ]
