# Generated by Django 3.2.6 on 2023-04-13 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_de_usuarios', '0002_auto_20230317_1759'),
        ('manejador_de_adendas', '0004_alter_registro_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adenda',
            name='autor_enfermero',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='manejador_de_usuarios.enfermero'),
        ),
        migrations.AlterField(
            model_name='adenda',
            name='autor_medico',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='manejador_de_usuarios.medico'),
        ),
    ]
