# Generated by Django 3.2.6 on 2023-04-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_de_adendas', '0005_auto_20230412_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
