# Generated by Django 3.2.6 on 2023-05-04 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_de_usuarios', '0002_auto_20230317_1759'),
        ('manejador_de_registros_de_historias_clinicas', '0008_alter_historia_clinica_fecha'),
        ('manejador_de_adendas', '0006_alter_registro_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nit', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=50)),
                ('ips', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='manejador_de_adendas.ips')),
                ('ips_doctor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manejador_de_usuarios.medico')),
            ],
        ),
        migrations.RemoveField(
            model_name='adenda',
            name='registros',
        ),
        migrations.AddField(
            model_name='adenda',
            name='diagnostico',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adenda',
            name='historia_clinica',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='manejador_de_registros_de_historias_clinicas.historia_clinica'),
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
        migrations.AddField(
            model_name='adenda',
            name='servicios',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='manejador_de_adendas.servicio'),
        ),
    ]
