# Generated by Django 3.2.6 on 2023-05-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_de_adendas', '0007_auto_20230504_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adenda',
            name='diagnostico',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
