# Generated by Django 3.2.6 on 2023-05-04 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_de_adendas', '0008_alter_adenda_diagnostico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adenda',
            old_name='servicios',
            new_name='servicio',
        ),
    ]
