# Generated by Django 3.2.6 on 2023-05-04 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_de_registros_de_historias_clinicas', '0009_remove_historia_clinica_id_historia_clinica'),
        ('manejador_de_adendas', '0009_rename_servicios_adenda_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adenda',
            name='id',
        ),
        migrations.AlterField(
            model_name='adenda',
            name='historia_clinica',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='manejador_de_registros_de_historias_clinicas.historia_clinica'),
        ),
    ]
