# Generated by Django 3.2.6 on 2023-05-26 02:34

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nit', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=50)),
                ('ips_doctor', models.IntegerField(default=None)),
                ('ips', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='adenda.ips')),
            ],
        ),
        migrations.CreateModel(
            name='Adenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historia_clinica', models.IntegerField(default=None)),
                ('diagnostico', django_cryptography.fields.encrypt(models.CharField(default=None, max_length=50))),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tema', django_cryptography.fields.encrypt(models.CharField(default=None, max_length=50))),
                ('descripcion', django_cryptography.fields.encrypt(models.CharField(default=None, max_length=100))),
                ('autor_medico', models.IntegerField(default=None)),
                ('autor_enfermero', models.IntegerField(default=None)),
                ('servicio', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='adenda.servicio')),
            ],
        ),
    ]
